<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nomad">

    <!--
	 The definitions for the main pad of the rover, to which
	 everything else is connected. This is the "base_link"
     of the rover model.
	 -->
    <xacro:property name="mainPadLength"  value="0.356" />
    <xacro:property name="mainPadWidth"   value="0.203" />
    <xacro:property name="mainPadHeight"  value="0.013" />
    <xacro:property name="mainPadX" value="-0.139" />
    <xacro:property name="mainPadY" value="0.0" />
    <xacro:property name="mainPadZ" value="0.198" />

    <!--
	 The definitions for the cameras.
	 -->
    <xacro:property name="cameraRadius"   value="0.015" />
    <xacro:property name="cameraLength"   value="0.030" />
    <xacro:property name="cameraFX"       value="0.0" />
    <xacro:property name="cameraFY"       value="0.0" />
    <xacro:property name="cameraFZ"       value="0.026" />

    <!--
	 The definitions for the wheels.
	 -->
    <xacro:property name="wheelRadius"    value="0.096" />
    <xacro:property name="wheelWidth"     value="0.050" />
    <xacro:property name="wheelTrack"     value="0.307" />
    <xacro:property name="axleHeight"     value="${wheelRadius}" />

    <!--
	 The definitions for the lidar.
	 -->
    <xacro:property name="lidarLength"    value="0.085" />
    <xacro:property name="lidarRadius"    value="0.065" />
    <xacro:property name="lidarOriginX"   value="0.0" />
    <xacro:property name="lidarOriginY"   value="0.0" />
    <xacro:property name="lidarOriginZ"   value="0.333" />

    <!--
	 The definitions for the ultrasonic rangefinders.
	 -->
    <xacro:property name="ultraLength"    value="0.020" />
    <xacro:property name="ultraRadius"    value="0.008" />
    <xacro:property name="ultraOriginXF"  value="0.055" />
    <xacro:property name="ultraOriginXB"  value="-0.330" />
    <xacro:property name="ultraOriginY"   value="0.070" />
    <xacro:property name="ultraOriginZ"   value="0.187" />
    <xacro:property name="ultraUp"        value="-0.1" />
    <xacro:property name="ultraOut"       value="0.05" />

    <link name="base_link">
        <visual>
            <origin xyz="${mainPadX} ${mainPadY} ${mainPadZ}" rpy="0 0 0" />
            <geometry>
                <box size="${mainPadLength} ${mainPadWidth} ${mainPadHeight}" />
            </geometry>
            <material name="blue">
				<color rgba="0 0 .8 1"/>
			</material>
        </visual>
    </link>

    <joint name="base_link_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${wheelTrack/2} ${wheelRadius}"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}" />
            </geometry>
        </visual>
    </link>

    <joint name="base_link_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 -${wheelTrack/2} ${wheelRadius}"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}" />
            </geometry>
        </visual>
    </link>

    <joint name="base_link_to_laser" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="${lidarOriginX} ${lidarOriginY} ${lidarOriginZ}"/>
    </joint>

    <link name="laser">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${lidarLength}" radius="${lidarRadius}" />
            </geometry>
        </visual>
    </link>

    <joint name="base_link_to_camera_front" type="fixed">
        <parent link="base_link"/>
        <child link="camera_front"/>
        <origin
            xyz="${cameraFX} ${cameraFY} ${mainPadZ + cameraFZ}"
            rpy="-1.57 0 -1.57"
            />
    </joint>

    <link name="camera_front">
        <visual>
            <origin xyz="0 0 0" />
            <geometry>
                <cylinder length="${cameraLength}" radius="${cameraRadius}" />
            </geometry>
        </visual>
    </link>

</robot>
