<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nomad">

    <!--
	 The definitions for the main pad of the rover, to which
	 everything else is connected. This is the "base_link"
     of the rover model.
	 -->
    <xacro:property name="mainPadLength"  value="0.356" />
    <xacro:property name="mainPadWidth"   value="0.203" />
    <xacro:property name="mainPadHeight"  value="0.013" />
    <xacro:property name="mainPadOriginX" value="-0.139" />
    <xacro:property name="mainPadOriginY" value="0.0" />
    <xacro:property name="mainPadOriginZ" value="0.190" />

    <!--
	 The definitions for the wheels.
	 -->
    <xacro:property name="wheelRadius"    value="0.096" />
    <xacro:property name="wheelWidth"     value="0.050" />
    <xacro:property name="wheelTrack"     value="0.307" />
    <xacro:property name="axleHeight"     value="${wheelRadius}" />

    <link name="base_link">
        <visual>
            <origin xyz="${mainPadOriginX} ${mainPadOriginY} ${mainPadOriginZ}" rpy="0 0 0" />
            <geometry>
                <box size="${mainPadLength} ${mainPadWidth} ${mainPadHeight}" />
            </geometry>
            <material name="blue">
				<color rgba="0 0 .8 1"/>
			</material>
        </visual>
    </link>

    <joint name="base_link_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${wheelTrack/2} ${wheelRadius}"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}" />
            </geometry>
        </visual>
    </link>

    <joint name="base_link_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 -${wheelTrack/2} ${wheelRadius}"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder length="${wheelWidth}" radius="${wheelRadius}" />
            </geometry>
        </visual>
    </link>

</robot>
