# how far away we can detect obstacles
obstacle_range: 2.5
raytrace_range: 3.0

# footprint of the robot
# TODO this is taken from a tutorial, and should be updated to the actual values
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

# how close to our robot we will tolerate obstacles
# this creates a "bubble" with very high cost around all obstacles
inflation_radius: 0.5

# we have information about obstacles from our IR laser
observation_sources: laser_scan_sensor
laser_scan_sensor: { sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true }
