<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robomagellan">

    <xacro:property name="mainLength" value="0.295" />
    <xacro:property name="mainWidth" value="0.220" />
    <xacro:property name="mainHeight" value="0.184" />
    <xacro:property name="axleHeight" value="0.049" />
    <xacro:property name="imuHeight" value="0.743" />
    <xacro:property name="laserHeight" value="0.270" />

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>
    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    <material name="yellow">
        <color rgba="0 0.5 0.5 1"/>
    </material>

    <link name="base_footprint"/>

    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>

        <origin xyz="0.093 0.0 ${axleHeight}" />
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="-0.093 0.0 0.072" rpy="0 0 0" />
            <geometry>
                <box size="${mainLength} ${mainWidth} ${mainHeight}" />
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_link_to_left_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="left_wheel"/>

        <origin xyz="0.0 0.135 0.0" />
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="1.570 0 0" />
            <geometry>
                <cylinder radius="0.055" length="0.053" />
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <joint name="base_link_to_right_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="right_wheel"/>

        <origin xyz="0.0 -0.135 0.0" />
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="-1.570 0 0" />
            <geometry>
                <cylinder radius="0.055" length="0.053" />
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <joint name="base_link_to_imu" type="fixed">
        <parent link="base_link"/>
        <child link="imu"/>

        <origin xyz="-0.098 0.110 ${imuHeight-axleHeight}" />
    </joint>

    <link name="imu">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.055" length="0.053" />
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_link_to_camera_lens" type="fixed">
        <parent link="base_link"/>
        <child link="camera_lens"/>

        <origin xyz="0.065 0.000 0.203" />
    </joint>

    <link name="camera_lens">
    </link>

    <joint name="camera_lens_to_camera_lens_optical" type="fixed">
        <parent link="camera_lens"/>
        <child link="camera_lens_optical"/>

        <origin xyz="0 0 0" rpy="0.0 1.57 0.0" />
    </joint>

    <link name="camera_lens_optical">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="0.02" />
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <joint name="base_link_to_infrared_forward" type="fixed">
        <parent link="base_link"/>
        <child link="infrared_forward"/>

        <origin xyz="0.047 0.0 0.005"/>
    </joint>

    <link name="infrared_forward">
        <visual>
            <geometry>
                <box size="0.01 0.032 0.013" />
            </geometry>
            <material name="yellow"/>
        </visual>
    </link>

    <joint name="base_link_to_infrared_aft" type="fixed">
        <parent link="base_link"/>
        <child link="infrared_aft"/>

        <origin xyz="-0.23 0.0 0.034" rpy="0.0 0.0 3.1415"/>
    </joint>

    <link name="infrared_aft">
        <visual>
            <geometry>
                <box size="0.01 0.032 0.013" />
            </geometry>
            <material name="yellow"/>
        </visual>
    </link>

    <joint name="base_link_to_laser" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>

        <origin xyz="0.010 0.004 ${laserHeight-axleHeight}"
                rpy="0.0 0.0 -0.02"/>
    </joint>

    <link name="laser">
        <visual>
            <geometry>
                <box size="0.060 0.060 0.085" />
            </geometry>
            <material name="green"/>
        </visual>
    </link>

</robot>
